### ISSUE TITLE
Issue with redbetter

### ISSUE THREAD

**Issue by tuningman9790** [iw00t/REDBetter#12]
So recently i've been uploading and when i do redactedbetter, it doesn't want to transcode them it just says 
"user1@server:~$ ~/REDBetter/redactedbetter
Logging in to RED...
Searching for transcode candidates..."

Now i know there's minimum of 9 releases that still need transcoding. So i tried
user1@server:~$ ~/REDBetter/redactedbetter 'https://redacted.ch/torrents.php?id=1394367&torrentid=2967656'
Logging in to RED...
Traceback (most recent call last):
  File "/home/user1/REDBetter/redactedbetter", line 276, in <module>
    main()
  File "/home/user1/REDBetter/redactedbetter", line 132, in main
    api = redactedapi.RedactedAPI(username, password, session_cookie)
  File "/home/user1/REDBetter/redactedapi.py", line 80, in __init__
    self._login()
  File "/home/user1/REDBetter/redactedapi.py", line 90, in _login
    self._login_username_password()
  File "/home/user1/REDBetter/redactedapi.py", line 119, in _login_username_password
    accountinfo = self.request('index')
  File "/home/user1/REDBetter/redactedapi.py", line 153, in request
    raise RequestException
redactedapi.RequestException

Any reason why this wouldn't work?

**Comment by inmedimptorolta** [comment]
I usually see this when you hit the login wall, wait a minute and retry the script to see if it lets you log in.

**Comment by tofkentof** [comment]
I am facing the exact same issue. Tried to run the script twice with a sleep of 600 seconds in the 2 executions but did not help.
Any idea?
