### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by straw-son** [iw00t/REDBetter#13]
Used to work fine for a while, uploading ~150 transcodes, but now it just quits with the following error message:

```
[user@pi]$ python2 redactedbetter
Logging in to RED...
Searching for transcode candidates...
Traceback (most recent call last):
  File "redactedbetter", line 276, in <module>
    main()
  File "redactedbetter", line 157, in main
    artist = group['group']['musicInfo']['artists'][0]['name']
IndexError: list index out of range
```

This was mentioned in red's forum, but it seems unanswered.

**Comment by undaunt** [comment]
Same situation here, won't go past a certain amount of transcodes. Even with cache, it gets two into the same run on each subsequent attempt then fails out. Happy to provide any info required to help troubleshoot.
